# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ec2-user/mobakit-repo123
# hooks:
#   ApplicationStop:
#     - location: scripts/application_stop.sh
#       timeout: 300
#       runas: ec2-user
#   BeforeInstall:
#     - location: scripts/before_install.sh
#       timeout: 300
#       runas: ec2-user
#   ApplicationStart:
#     - locat ion: scripts/application_start.sh
#       timeout: 300
#       runas: ec2-user

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mobakit-repo123
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
